apiVersion: v1
kind: Service
metadata:
  name: cinema-service
spec:
  type: NodePort
  selector:
    app: cinema-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30002
