apiVersion: v1
kind: Service
metadata:
  name: filme-service
spec:
  type: NodePort
  selector:
    app: filme-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003
