name: CI

on:
  push:
    branches:
      - main  # Ou 'master', se esse for o nome da sua branch
  pull_request:
    branches:
      - main  # Ou 'master', se esse for o nome da sua branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
name: CI Pipeline

on:
  push:
    branches:
      - master  # Ou 'master', se esse for o nome da sua branch
  pull_request:
    branches:
      - master  # Ou 'master', se esse for o nome da sua branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
